# retry error code

var balance = 100
var db = false
var tryToSuccess = 3

func main() {
log.SetFlags(log.Ltime)
amount, err := withdraw(200)
if err != nil {
log.Fatal("main :", err)
}
fmt.Println(" Withdrawal successing", amount)
}

func withdraw(amount int) (int, error) {
balance, err := getBalance()
if err != nil {
return 0, fmt.Errorf("withdraw : %v", err)
}
if amount > balance {
return 0, errors.New("withdraw F: amount not enough to withdrawal")
}
return amount, nil
}

func getBalance() (int, error) {
if !db {
if err := waitForDb(); err != nil {
return 0, fmt.Errorf("getBalance %v ", err)
}

}
return balance, nil
}
func connectDB(nTry int) error {
if nTry == tryToSuccess {
return nil
}
return errors.New("db is busy")
}

func waitForDb() error {
timeout := 3 \* time.Second
deadline := time.Now().Add(timeout)

for tries := 0; time.Now().Before(deadline); tries++ {
err := connectDB(tries)
if err == nil {
return nil
}
log.Printf("database is not responding %v retrying...", err)
time.Sleep(time.Second << tries)
}

return fmt.Errorf("waitForDb timeout :%v", timeout)
}
